# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-05 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preflowcore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restroom',
            name='floor',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='restroom',
            name='is_single_occupancy',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='restroom',
            name='stalls',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restroom',
            name='toilet_seat_covers',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='unit_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='restroom',
            name='flush_type',
            field=models.CharField(blank=True, choices=[(1, 'Automatic'), (2, 'Manual'), (3, 'Water Saving'), (4, 'None'), (5, 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='restroom',
            name='hand_dryer_type',
            field=models.CharField(blank=True, choices=[(1, 'Button'), (2, 'Sensor'), (3, 'None'), (4, 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='restroom',
            name='hand_soap_dispenser_type',
            field=models.CharField(blank=True, choices=[(1, 'Automatic'), (2, 'Manual'), (3, 'Bar'), (4, 'None'), (5, 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='restroom',
            name='sex',
            field=models.CharField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'No Distinction'), (4, 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='restroom',
            name='toilet_paper_dispenser_type',
            field=models.CharField(blank=True, choices=[(1, 'Perpendicular'), (2, 'Parallel'), (3, 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='restroom',
            name='towel_dispenser_type',
            field=models.CharField(blank=True, choices=[(1, 'Manual'), (2, 'Automatic'), (3, 'Other'), (4, 'None')], max_length=100),
        ),
    ]
